# Generated by Django 5.0.4 on 2024-05-31 23:00

import comercio.models
import django.db.models.deletion
import django_bunny.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('estrellas', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to=comercio.models.Comercio.cliente_logo_path)),
                ('portada', models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to=comercio.models.Comercio.cliente_portada_path)),
                ('tipo', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=200)),
                ('importancia', models.IntegerField()),
                ('detalles', models.TextField()),
                ('camara', models.CharField(default='Ninguna', max_length=80)),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
                ('resumen', models.TextField()),
                ('qr', models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to=comercio.models.Comercio.cliente_qr_path)),
                ('estado', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to=comercio.models.Imagen.cliente_galeria_path)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='comercio.comercio')),
            ],
        ),
    ]
