# Generated by Django 4.1.7 on 2024-02-22 17:53

from django.db import migrations, models
import django_bunny.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellidom', models.CharField(max_length=250)),
                ('apellidop', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=10000)),
                ('puesto', models.CharField(max_length=250)),
                ('foto_perfil', models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to='perfil_personal/')),
                ('foto_portada', models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to='portada_personal/')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
    ]
