# Generated by Django 4.1.7 on 2024-02-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='mison',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='vision',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='puesto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
