# Generated by Django 5.0.4 on 2024-05-31 22:59

import camaras.models
import django.db.models.deletion
import django_bunny.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2500)),
                ('key', models.CharField(max_length=2500)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
            },
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('municipio', models.CharField(max_length=250)),
                ('background', models.ImageField(storage=django_bunny.storage.BunnyStorage(), upload_to=camaras.models.Camara.camara_background_path)),
                ('background_dark', models.ImageField(storage=django_bunny.storage.BunnyStorage(), upload_to=camaras.models.Camara.camara_background_dark_path)),
                ('camdisp', models.BooleanField(default=True)),
                ('createdAt', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('etiquetauno', models.TextField()),
                ('etiquetados', models.TextField()),
                ('etiquetatres', models.TextField()),
                ('etiquetacuatro', models.TextField()),
                ('logo', models.ImageField(storage=django_bunny.storage.BunnyStorage(), upload_to=camaras.models.Camara.camara_logo_path)),
                ('latitude', models.CharField(max_length=250)),
                ('longitude', models.CharField(max_length=250)),
                ('likes', models.IntegerField(default=0)),
                ('pin', models.ImageField(storage=django_bunny.storage.BunnyStorage(), upload_to=camaras.models.Camara.camara_background_path)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='camaras.stream')),
            ],
            options={
                'verbose_name': 'Camara',
                'verbose_name_plural': 'Camaras',
            },
        ),
    ]
