# Generated by Django 4.1.7 on 2024-02-12 07:08

from django.db import migrations, models
import django.db.models.deletion
import django_bunny.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.URLField(max_length=2500)),
                ('color', models.CharField(max_length=250)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=2500)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2500)),
                ('key', models.CharField(max_length=2500)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('municipio', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('cp', models.CharField(max_length=25)),
                ('imagen_picture', models.ImageField(storage=django_bunny.storage.BunnyStorage(), upload_to='Lugar-pictures/')),
                ('imagen_fondo', models.ImageField(storage=django_bunny.storage.BunnyStorage(), upload_to='Lugar-wallpaper/')),
                ('descripcion', models.TextField(max_length=2500)),
                ('puntuacion', models.FloatField(default=0.0)),
                ('activo', models.BooleanField(default=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='camaras.stream')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.FloatField(default=0.0)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='camaras.lugar')),
            ],
            options={
                'verbose_name': 'Hora',
                'verbose_name_plural': 'Horas',
            },
        ),
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='camaras.etiqueta')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='camaras.lugar')),
            ],
            options={
                'verbose_name': 'Caracteristica',
                'verbose_name_plural': 'Caracteristicas',
                'unique_together': {('lugar', 'etiqueta')},
            },
        ),
    ]
