# Generated by Django 5.0.4 on 2024-05-31 23:49

import camaras.models
import django_bunny.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='background_dark_web',
            field=models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to=camaras.models.Camara.camara_background_dark_path),
        ),
        migrations.AddField(
            model_name='camara',
            name='background_web',
            field=models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to=camaras.models.Camara.camara_background_path),
        ),
        migrations.AlterField(
            model_name='camara',
            name='background',
            field=models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to=camaras.models.Camara.camara_background_path),
        ),
        migrations.AlterField(
            model_name='camara',
            name='background_dark',
            field=models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to=camaras.models.Camara.camara_background_dark_path),
        ),
    ]
