# Generated by Django 5.0.4 on 2024-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0003_alter_camara_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
