# Generated by Django 5.0.4 on 2024-06-04 01:55

import django_bunny.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to='comentarios/'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
