# Generated by Django 5.0.4 on 2024-06-04 02:21

import django_bunny.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_comentario_imagen_alter_comentario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='https://staticurix.b-cdn.net/Recursos%20WEB/DEFAULT/perfildefault.jpg', null=True, storage=django_bunny.storage.BunnyStorage(), upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto_portada',
            field=models.ImageField(blank=True, default='https://staticurix.b-cdn.net/Recursos%20WEB/DEFAULT/portadadefault.jpg', null=True, storage=django_bunny.storage.BunnyStorage(), upload_to='fotos_portada/'),
        ),
    ]
