# Generated by Django 5.0.4 on 2024-06-04 02:23

import django_bunny.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_customuser_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='/Recursos%20WEB/DEFAULT/perfildefault.jpg', null=True, storage=django_bunny.storage.BunnyStorage(), upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto_portada',
            field=models.ImageField(blank=True, default='/Recursos%20WEB/DEFAULT/portadadefault.jpg', null=True, storage=django_bunny.storage.BunnyStorage(), upload_to='fotos_portada/'),
        ),
    ]
