# Generated by Django 5.0.4 on 2024-06-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_comentario_camara_comentario_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
