# Generated by Django 5.0.4 on 2024-06-07 20:14

import django_bunny.storage
import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_imagenesdefault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesdefault',
            name='imagen',
            field=models.ImageField(storage=django_bunny.storage.BunnyStorage(), upload_to=login.models.ImagenesDefault.cliente_logo_path),
        ),
    ]
