# Generated by Django 5.0.4 on 2024-06-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_imagenesdefault_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_avatar_uploaded',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.URLField(default='https://staticurix.b-cdn.net/Default/Perfil/huasca.jpg'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto_portada',
            field=models.URLField(default='https://staticurix.b-cdn.net/Default/Portada/portada_1.jpg'),
        ),
    ]
