# Generated by Django 5.0.4 on 2024-07-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='empresa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
