# Generated by Django 5.0.4 on 2024-07-06 00:20

import django.db.models.deletion
import django_bunny.storage
import evento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0006_alter_camara_background_dark_and_more'),
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('direccion', models.TextField()),
                ('estado', models.CharField(max_length=250)),
                ('municipio', models.CharField(max_length=250)),
                ('logo', models.ImageField(blank=True, max_length=250, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to=evento.models.EventoCultural.camara_logo_path)),
                ('detalles', models.TextField()),
                ('cobertura', models.CharField(choices=[('No', 'Sin cobertura'), ('Si', 'Con cobertura')], default='Si', max_length=50)),
                ('promocion', models.IntegerField(default=0)),
                ('espectadores', models.IntegerField(default=0)),
                ('camara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camaras.camara')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camaras.stream')),
            ],
            options={
                'verbose_name': 'Evento cultural',
                'verbose_name_plural': 'Eventos culturales',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to=evento.models.Imagen.evento_galeria_path)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='evento.eventocultural')),
            ],
        ),
    ]
